//
//  UIFont+KPAdditions.swift
//
//  Generated by Zeplin on 12/19/17.
//  Copyright (c) 2017 Kinopub. All rights reserved.
//

import UIKit

extension UIFont {
    
    class var textSmall: UIFont {
        return UIFont.systemFont(ofSize: 12.0, weight: .regular)
    }
    
    class var kpMovieRatings: UIFont {
        return UIFont.systemFont(ofSize: 17.0, weight: .semibold)
    }
    
    class var titleTitle4Centred: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .regular)
    }
    
    class var textRegular: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .regular)
    }
    
    class var textSmallCentred: UIFont {
        return UIFont.systemFont(ofSize: 12.0, weight: .regular)
    }
    
    class var titleTitle4: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .regular)
    }
    
    class var buttonText: UIFont {
        return UIFont.systemFont(ofSize: 15.0, weight: .regular)
    }
    
    class var titleLarge: UIFont {
        return UIFont.systemFont(ofSize: 34.0, weight: .bold)
    }
    
    class var textBig: UIFont {
        return UIFont.systemFont(ofSize: 17.0, weight: .regular)
    }
    
    class var titleSmall: UIFont {
        return UIFont(name: "UniSansSemiBold", size: 12.0)!
    }
    
    class var linkRegular: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .regular)
    }
    
    class var kpMovieInfo: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .regular)
    }
    
    class var kpMovieTitle2: UIFont {
        return UIFont.systemFont(ofSize: 17.0, weight: .regular)
    }
    
    class var kpMovieTitle1: UIFont {
        return UIFont.systemFont(ofSize: 20.0, weight: .regular)
    }
    
    class var titleTitle2: UIFont {
        return UIFont.systemFont(ofSize: 20.0, weight: .semibold)
    }
    
    class var labelBigCounter: UIFont {
        return UIFont(name: "UniSansBold", size: 14.0)!
    }
    
    class var attentionRegular: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .regular)
    }
    
    class var labelRegular: UIFont {
        return UIFont(name: "UniSansSemiBold", size: 9.0)!
    }
    
    class var actionButtonText: UIFont {
        return UIFont(name: "UniSansSemiBold", size: 12.0)!
    }
    
    class var kpMovieRatingsSmall: UIFont {
        return UIFont.systemFont(ofSize: 12.0, weight: .semibold)
    }
    
}
